- name: Pacman operations
  when: ansible_os_family == "Archlinux"
  tags:
    - pacman
  vars:
    package_list: []
  block:
    - name: Get import(dependencies) profiles
      loop: "{{ enable_profiles }}"
      when: profiles[item].import is defined
      ansible.builtin.set_fact:
        enable_profiles: "{{ (enable_profiles + profiles[item].import) | unique }}"

    - name: List profiles
      when: debug_enabled
      ansible.builtin.debug:
        var: enable_profiles

    - name: Get packages
      ansible.builtin.set_fact:
        package_list: "{{ package_list + profiles[item].pacman }}"
      when: profiles[item].pacman is defined
      loop: "{{ enable_profiles }}"

    - name: List packages
      when: debug_enabled
      ansible.builtin.debug:
        var: package_list

    - name: Get explicit installed packages output
      ansible.builtin.shell: pacman -Qne
      changed_when: false
      register: list_output

    - name: Get explicit installed packages
      ansible.builtin.set_fact:
        explicit_installed_list: "{{ list_output.stdout_lines | map('regex_replace', '^(\\S+)\\s+\\S+', '\\1') }}"

    - name: List explicit installed packages
      when: debug_enabled
      ansible.builtin.debug:
        var: explicit_installed_list

    - name: Get installed packages you might want to uninstall
      ansible.builtin.set_fact:
        might_uninstalls: "{{ explicit_installed_list | difference(package_list) }}"

    - name: List packages you might want to uninstall
      when: debug_enabled
      ansible.builtin.debug:
        var: might_uninstalls
