#!/usr/bin/env python3

import json
import os
import subprocess

def reload():
    """Run scripts to reload all program's colorsheme config"""
    subprocess.run(["sh", "./scripts/reload.sh"])

def export_xrdb(config: dict):
    """Export xrdb file"""
    with open(os.environ["XDG_CONFIG_HOME"]+"/x11/xresources.d/test", "w") as xrdb_file:
        print("! this gen from color file", file=xrdb_file)
        print(f'*.background: {config["special"]["background"]}', file=xrdb_file)

def main():

    with open("color.json") as config_file:
        config: dict = json.load(config_file)

    export_xrdb(config)
    reload()

if __name__ == "__main__":
    main()
