#!/bin/sh
#vi:syntax=sh

# TODO edit hard code re source config file
# Shortcut: Reload config file
alias rebash="source $HOME/.config/bash/bashrc"
alias rezsh="source $HOME/.config/zsh/.zshrc"

alias cf="cd ~/.config"
alias lcs="cd ~/.local/share"
alias lcb="cd ~/.local/bin"
alias cfn="$EDITOR ~/.config/nvim/"
alias cfz="$EDITOR ~/.config/zsh/.zshrc"
alias cfa="$EDITOR ~/.config/shell/aliases"
alias cfp="$EDITOR ~/.config/shell/profile"
alias cft="$EDITOR ~/.config/tmux/tmux.conf"

# Tmux
alias ta="tmux a"
alias tls="tmux ls"
alias tks="tmux kill-sess"

# Git shortcut
alias g="git"
alias gst="git status"
alias gss="git status --short"
alias ga="git add"
alias gaa="git add --all --verbose"
alias gc="git commit"
alias gu="git rm --cached --force" 
alias gb="git branch"
alias gba="git branch --all"
alias gbd="git branch --delete"
alias gbD="git branch -D"
alias gco="git checkout"
alias gwt="git worktree"
alias grb="git rebase"
alias grbi="git rebase -i"
alias gm="git merge"
alias gp="git pull"
alias gP="git push"
alias ggraph="git log --graph --oneline --decorate"

# LazyGit
alias gz="lazygit"
alias lazydot="lazygit --git-dir=/home/pk/.dotfile.git --work-tree=/home/pk"
alias dz="lazydot"

# Colorize output
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# Confirm file operation
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# Utilities
alias vi="nvim"
alias lv="lvim"
alias dot="git --git-dir=$DOTFILES --work-tree=$HOME"
alias colortest="msgcat --color=test"

# ls Flags
alias l="ls -CF"
alias ll="ls -lAFrt"
alias la="ls -lAF --group-directories-first"
alias lh="ls -lAFhS"

# Check disk space
alias df="df -h"
alias free="free -m"
alias duh="du -h --max-depth=1"
