#!/bin/sh
#vi:syntax=sh

# TODO edit hard code re source config file
# Shortcut: Reload config file
alias rebash="source $HOME/.config/bash/bashrc"
alias rezsh="source $HOME/.config/zsh/.zshrc"

alias cf='cd ~/.config'
alias dt='cd ~/.local/share'
alias db='cd ~/.local/bin'
alias cfn='$EDITOR ~/.config/nvim/'
alias cfz='$EDITOR ~/.config/zsh/.zshrc'
alias cfa='$EDITOR ~/.config/shell/aliases'
alias cfp='$EDITOR ~/.config/shell/profile'
alias cft='$EDITOR ~/.config/tmux/tmux.conf'

# Tmux
alias ta="tmux a"
alias tls="tmux ls"
alias tks="tmux kill-sess"

# Git shortcut
alias gs='git status'

# LazyGit
alias zg="lazygit"
alias lazydot="lazygit --git-dir=/home/pk/.dotfile.git --work-tree=/home/pk"
alias zd="lazydot"

# Colorize output
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Confirm file operation
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Utilities
alias vi="nvim"
alias lv="lvim"
alias dot="git --git-dir=$DOTFILES --work-tree=$HOME"
alias colortest='msgcat --color=test'

# ls Flags
alias l='ls -CF'
alias ll='ls -lAFrt'
alias la='ls -lAF --group-directories-first'
alias lh='ls -lAFhS'

# Check disk space
alias df='df -h'
alias free='free -m'
alias duh='du -h --max-depth=1'
