#!/bin/sh
#    ██████╗ ██████╗  ██████╗ ███████╗██╗██╗     ███████╗
#    ██╔══██╗██╔══██╗██╔═══██╗██╔════╝██║██║     ██╔════╝
#    ██████╔╝██████╔╝██║   ██║█████╗  ██║██║     █████╗  
#    ██╔═══╝ ██╔══██╗██║   ██║██╔══╝  ██║██║     ██╔══╝  
# ██╗██║     ██║  ██║╚██████╔╝██║     ██║███████╗███████╗
# ╚═╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝

## XDG base directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# FIXME: don't work in bash
export PATH="${$(find ~/.local/bin -type d -printf %p:)%%:}:$PATH"

## Default program
export TERM="xterm-256color"
export EDITOR="nvim"
export VISUAL="nvim"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export TERMINAL="kitty"
export BROWSER="brave"

## Dotfile management
export DOTFILES=$HOME/.dotfile.git

## Home directory clean up
export XINITRC=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc
export HISTFILE=${XDG_STATE_HOME:-$HOME/.local/state}/history
export LESSHISTFILE="-"
export INPUTRC=${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc
export ZDOTDIR=${XDG_CONFIG_HOME:-$HOME/.config}/zsh
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export VIMINIT='let $MYVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/vimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYVIMRC'
export FZF_DEFAULT_OPTS="--reverse --cycle"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export STARSHIP_CONFIG=${XDG_CONFIG_HOME:-$HOME/.config}/starship/config.toml
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
# Node#npm
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc
# Rust#cargo
export CARGO_HOME=${XDG_DATA_HOME:-$HOME/.local/share}/cargo
export RUSTUP_HOME=${XDG_DATA_HOME:-$HOME/.local/share}/rustup
. "$XDG_DATA_HOME/cargo/env"

# if running bash
if [ -n "$BASH_VERSION" ]; then
    [[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc ]] && source ${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc
fi

if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  # exec startx "$XINITRC"
fi
