#!/bin/sh
#    ██████╗ ██████╗  ██████╗ ███████╗██╗██╗     ███████╗
#    ██╔══██╗██╔══██╗██╔═══██╗██╔════╝██║██║     ██╔════╝
#    ██████╔╝██████╔╝██║   ██║█████╗  ██║██║     █████╗  
#    ██╔═══╝ ██╔══██╗██║   ██║██╔══╝  ██║██║     ██╔══╝  
# ██╗██║     ██║  ██║╚██████╔╝██║     ██║███████╗███████╗
# ╚═╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚══════╝

## XDG base directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

## MY environments vars
export DOTFILES=$HOME/.dotfile.git
export MY_SHELL="$(ps -p $$ -ocomm=)"
export MY_BIN="$HOME/bin"
export MY_LIB="$HOME/lib"
export MY_SRC="$HOME/.local/src"
export MY_BACKGROUND="dark"
export MY_COLOR_CACHE_DIR="$XDG_CACHE_HOME/colorsync"
export MY_NOTES_DIR=$HOME/notes

export PATH="$HOME/.local/bin:$PATH"
export PATH="$(echo $(find $MY_BIN -type d -printf %p:))$PATH"

## Default program
export TERM="xterm-256color"
export EDITOR="nvim"
export VISUAL="nvim"
export MANPAGER='nvim +Man!'
# export MANWIDTH=999
export TERMINAL="kitty"

if command -v firefox-nightly > /dev/null; then
  export BROWSER="firefox-nightly"
elif command -v firefox > /dev/null; then
  export BROWSER="firefox"
elif command -v brave > /dev/null; then
  export BROWSER="brave"
else
  export BROWSER="google-chrome-stable"
fi

## Home directory clean up
source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/xdg_clean.profile
source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/config.env

# if running bash
if [ -n "$BASH_VERSION" ]; then
    [ -f ${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc ] && source ${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc
fi

trap break SIGINT
startx_y_or_n() {
  if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    # exec startx
    while true; do
      printf "Do you want to startx? (y/n):"
      read yn
      case $yn in
        [Yy]* ) startx "$XINITRC"; break;;
        [Nn]* ) break;;
        * ) echo "(y/n) only";;
      esac
    done
  fi
}
startx_y_or_n

## End of file
