#!/usr/bin/env bash

set -euo pipefail

firmware_path=$HOME/.local/src/qmk_firmware
KEYBOARD="xiudi/xd75"
KEYMAP="my_maps"
keymap_path="$(pwd)/${KEYBOARD}/${KEYMAP}"

if [[ ! -d $firmware_path ]]; then
  echo $firmware_path
  mkdir -p ${firmware_path%%qmk_firmware}
  cd ${firmware_path%%qmk_firmware}
  qmk clone
fi

clear ()
{
  rm -rf "${firmware_path}/keyboards/${KEYBOARD}/keymaps/${KEYMAP}"
}

trap 'clear' ERR

cp -rf $keymap_path "${firmware_path}/keyboards/${KEYBOARD}/keymaps/${KEYMAP}"
cd $firmware_path

# util/docker_build.sh $KEYBOARD:$KEYMAP:flash
make $KEYBOARD:$KEYMAP:flash

exec xset r rate 300 50 & # refresh repeat rate (same as in .xprofile)

clear
