---
- name: Check packages
  hosts: all
  remote_user: pk
  # gather_facts: false
  vars_files:
    - ../vars/arch_laptop.yaml
  vars:
    debug_enabled: true
    enable_profiles:
      - core
      # - gpu
      # - gpu-util
      - xorg
  roles:
    - pacman
    # - aur
    # - systemd
