#!/usr/bin/env sh

# TODO: Is this really work?
# nvidia gpu only
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

userresources=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f "$userresources" ]; then
  xrdb -merge  "$userresources" 
else
  xrdb -merge  "$HOME/.Xresources"
fi

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# TODO: studies this
# start some nice programs

# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" 
else
  . "$HOME/.xprofile"
fi

# Reduce scale of display
# xrandr --output eDP1 --scale .85

# FIXME: not work when unplug keyboard
# Set key repeat delay 280 ms, 40 per sec
( sleep 1; xset r rate 300 50 ) &

# Switch between keyboard layouts
# list all key combinations `grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst`
# setxkbmap us,us -variant ,colemak_dh -option grp:win_space_toggle &
# exec setxkbmap us,th,us -variant ,,colemak_dh -option grp:alt_caps_toggle &
( sleep 1; setxkbmap us,th -option grp:alt_caps_toggle ) &

