#!/bin/sh

# Reduce scale of display
# xrandr --output eDP1 --scale .85

# Set key repeat delay 280 ms, 40 per sec
xset r rate 300 50 &

# Switch between keyboard layouts
# list all key combinations `grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst`
# setxkbmap us,us -variant ,colemak_dh -option grp:win_space_toggle &
setxkbmap us,th -option grp:alt_caps_toggle &

# Autostart program
nm-applet &
nitrogen --restore &
picom &
sxhkd &
$HOME/.config/polybar/launch.sh &

# Start window manager
exec bspwm
