hostname: laptop

# packages or services that must exists before any operations no matter what
# order of list indicate the order of package to install
pre_install:
  pacman:
  - pacman
  - git
  - etckeeper # use to track etc and all install package operations
  aur:
  - git
  - base-devel # need for commpile aur
  - paru-bin

# Packages Profiles
profiles:
  core: # NOTE: I don't think it will work
    pacman:
    # firmware
    - base
    - linux-firmware
    - linux-zen
    - linux-zen-headers # need for dkms
    - intel-ucode
    # initramfs
    - mkinitcpio-utils
    - mkinitcpio-dropbear
    - mkinitcpio-netconf
    # boot tools
    - grub
    - efibootmgr
    # filesystem
    - btrfs-progs
    - lvm2
    # networking
    - networkmanager
    - openssh
    - rsync
    - git
    # - opendoas
    - sudo
    systemd:
    - NetworkManager
    - sshd

  base-util:
    pacman:
    - stow
    - man-db
    - neovim
    - tmux

  gpu:
    import: [ core ]
    pacman:
    - mesa
    - xf86-video-intel
    - nvidia-dkms # for non-zen use nvidia
    - nvidia-utils

  gpu-util:
    import: [ gpu ]
    pacman:
    - nvtop
    aur:
    - optimus-manager
    systemd:
    - optimus-manager

  xorg:
    import: [ gpu, gpu-util ]
    pacman:
    - bspwm
    - xorg-server
    - xorg-xinit
    - xdotool
    - sxhkd
    - feh
    - dunst
    - picom
    - polybar
    - wezterm

  intensive:
    flatpak:
    - steam

  virtualisation:
