#!/bin/sh
options=$*
class_name="Term-menu"
# st -c "Term-menu" -g 40x8+297+1 -e bash -c "fzf $options < /proc/$$/fd/0 > /proc/$$/fd/1"

if [ -z "$(ps -ef | grep $class_name)" ]; then
  $TERMINAL --class "$class_name" -e bash -c "fzf $options < /proc/$$/fd/0 > /proc/$$/fd/1"
fi
