#!/bin/sh
options=$*
class_name="Term-menu"
window_id="$(xdotool search --class $class_name)"

if [ -z "$window_id" ]; then
  # st -c "Term-menu" -g 40x8+297+1 -e bash -c "fzf $options < /proc/$$/fd/0 > /proc/$$/fd/1"
  $TERMINAL --class "$class_name" -e bash -c "fzf $options < /proc/$$/fd/0 > /proc/$$/fd/1"
elif [ $(xdotool getwindowfocus) = "$window_id" ]; then
  xdotool windowkill "$window_id"
else
  xdotool windowactivate "$window_id"
fi
