#!/bin/sh

class=$1
shift
cmd=$*

if [ -z "$class" ] || [ -z "$cmd" ]; then
	echo "Usage: $0 <window classname> <command>"
	exit 1
fi

pid=$(xdotool search --class "$class")
[ -z "$pid" ] \
  && $TERMINAL --class "$class" $cmd \
  || xdotool windowkill "$pid"
