#!/bin/sh

set -euo pipefail

COMMAND=xdotool
[ -z "$(command -v $COMMAND)" ] && echo "${COMMAND} not found" && exit 1

help ()
{
  cat << EOF
Usage: $(basename $0) <classname> <x>% <y>% [center]
EOF
}

if [ $# -lt 3 ]; then
  help
  exit 1
fi

class=$1
x=$2
y=$3

OPTS="search --class ${class} windowsize --sync ${x}% ${y}%"

if [ $# -eq 4 ]; then
  move=$4
else
  move=""
fi

case $move in
  center)
    dx=$(expr \( 100 - ${x} \) / 2)
    dy=$(expr \( 100 - ${y} \) / 2)
    OPTS="${OPTS} windowmove --sync ${dx}% ${dy}%"
    ;;
  "") # do nothing
    ;;
  *) help
    ;;
esac

$COMMAND $OPTS

exit
