#!/bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c "$XDG_CONFIG_HOME/bspwm/sxhkdrc" &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2

# bspc config automatic_scheme spiral
# bspc config initial_polarity first_child
# bspc config removal_adjustment true

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color     "#d79921"
# bspc config normal_border_color      "#202A25"

bspc config focus_follows_pointer true
bspc config pointer_modifier      mod1
bspc config pointer_action1       move
bspc config pointer_action2       resize_corner


bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

source "${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/bspwm-func"

bspc rule -a Volume     sticky=on state=floating focus=on  center=on
bspc rule -a Monitoring sticky=on state=floating focus=on  center=on
bspc rule -a scratchpad sticky=on state=floating center=on focus=on
bspc rule -a Term-menu  sticky=on state=floating center=on

bspc_size Volume     50 50
bspc_size Monitoring 80 80
bspc_size scratchpad 85 75
bspc_size Term-menu  40 30

bspc_desktop 2 \
  Brave-browser \
  firefox \
  firefox-nightly \
  qutebrowser

bspc_desktop 3 \
  Thunderbird \
  discord \
  Steam

bspc_desktop 4 \
  easyeffects \
  obs
