#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c $XDG_CONFIG_HOME/bspwm/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_modifier      mod1
bspc config pointer_action1	      move
bspc config pointer_action2 	    resize_corner

bspc rule -a Brave-browser desktop='^2'
bspc rule -a Thunderbird desktop='^3'
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
