add_newline = false

[username]
format = "[$user]($style)@"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_only = false

[localip]
ssh_only = false

# Below generate by
# `starship preset plain-text-symbols >> ~/.config/starship/config.toml`
# `starship preset bracketed-segments >> ~/.config/starship/config.toml`
[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = "aws "

[azure]
symbol = "az "

[bun]
format = '\[[$symbol($version)]($style)\]'
symbol = "bun "

[c]
format = '\[[$symbol($version(-$name))]($style)\]'
symbol = "C "

[cobol]
format = '\[[$symbol($version)]($style)\]'
symbol = "cobol "

[conda]
format = '\[[$symbol$environment]($style)\]'
symbol = "conda "

[crystal]
format = '\[[$symbol($version)]($style)\]'
symbol = "cr "

[cmake]
format = '\[[$symbol($version)]($style)\]'
symbol = "cmake "

[daml]
format = '\[[$symbol($version)]($style)\]'
symbol = "daml "

[dart]
format = '\[[$symbol($version)]($style)\]'
symbol = "dart "

[deno]
format = '\[[$symbol($version)]($style)\]'
symbol = "deno "

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = "docker "

[erlang]
format = '\[[$symbol($version)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = "exs "

[elm]
format = '\[[$symbol($version)]($style)\]'
symbol = "elm "

[fennel]
format = '\[[$symbol($version)]($style)\]'
symbol = "fnl "

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "fossil "

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
symbol = "gcp "

[git_branch]
format = '\[[[$symbol](red bold)$branch]($style)\]'
symbol = "G"

[gleam]
symbol = "gleam "

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = "go "

[gradle]
format = '\[[$symbol($version)]($style)\]'
symbol = "gradle "

[guix_shell]
format = '\[[$symbol]($style)\]'
symbol = "guix "

[haskell]
format = '\[[$symbol($version)]($style)\]'

[haxe]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "hg "

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = "java "

[julia]
format = '\[[$symbol($version)]($style)\]'
symbol = "jl "

[kotlin]
format = '\[[$symbol($version)]($style)\]'
symbol = "kt "

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = "lua "

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = "nodejs "

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = "memory "

[meson]
format = '\[[$symbol$project]($style)\]'
symbol = "meson "

[nats]
symbol = "nats "

[nim]
format = '\[[$symbol($version)]($style)\]'
symbol = "nim "

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
symbol = "nix "

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
symbol = "ml "

[opa]
format = '\[[$symbol($version)]($style)\]'
symbol = "opa "

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Void = "void "
Windows = "win "

[package]
format = '\[[$symbol$version]($style)\]'
symbol = "pkg "

[perl]
format = '\[[$symbol($version)]($style)\]'
symbol = "pl "

[php]
format = '\[[$symbol($version)]($style)\]'
symbol = "php "

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'
symbol = "pijul "

[pulumi]
format = '\[[$symbol$stack]($style)\]'
symbol = "pulumi "

[purescript]
format = '\[[$symbol($version)]($style)\]'
symbol = "purs "

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "py "

[quarto]
symbol = "quarto "

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'
symbol = "raku "

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = "rb "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "rs "

[scala]
format = '\[[$symbol($version)]($style)\]'
symbol = "scala "

[spack]
format = '\[[$symbol$environment]($style)\]'
symbol = "spack "

[solidity]
format = '\[[$symbol($version)]($style)\]'
symbol = "solidity "

[status]
symbol = "[x](bold red) "

[sudo]
format = '\[[as $symbol]($style)\]'
symbol = "sudo "

[swift]
format = '\[[$symbol($version)]($style)\]'
symbol = "swift "

[typst]
symbol = "typst "

[terraform]
symbol = "terraform "

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
symbol = "zig "
